# -*- coding: utf-8 -*-
"""02_optuna_tuning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NzaYTfkgnGHebxQ8B2uD9rkkmUz9UWS
"""

!pip install datasets optuna --quiet

import os, time, pickle
import pandas as pd
import numpy as np
from datasets import load_dataset
import optuna
from sklearn.pipeline import Pipeline
from sklearn.metrics import (roc_auc_score, accuracy_score, f1_score,
                              average_precision_score, confusion_matrix)
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

import sys
sys.path.append('..')
from src.features import URLFeatureExtractor

optuna.logging.set_verbosity(optuna.logging.WARNING)
os.makedirs('models',  exist_ok=True)
os.makedirs('reports', exist_ok=True)

# 1. Load Data & Whitelist

print("Loading PhreshPhish...")
df_train = pd.read_csv('data/df_train.csv')
df_test  = pd.read_csv('data/df_test.csv')
df_train['binary_label'] = (df_train['label'] == 'benign').astype(int)
df_test['binary_label'] = (df_test['label'] == 'benign').astype(int)

TRUSTED_DOMAINS = pickle.load(open('models/trusted_domains.pkl', 'rb'))

train_urls = df_train['url'].values
y_train    = df_train['binary_label'].values
test_urls  = df_test['url'].values
y_test     = df_test['binary_label'].values

print(f"Train: {len(train_urls):,}  |  Test: {len(test_urls):,}")
print(f"Whitelist: {len(TRUSTED_DOMAINS):,} domains")

# 2. Build Tuning Subsample

urls_sub, _, y_sub, _ = train_test_split(
    train_urls, y_train,
    train_size=100_000,
    stratify=y_train,
    random_state=42
)

print(f"Tuning subsample : {len(urls_sub):,} URLs")
print(f"  Phishing : {(y_sub==0).sum():,}")
print(f"  Benign   : {(y_sub==1).sum():,}")

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# 3. Objective Functions

def objective_xgb(trial):
    params = {
        'n_estimators':     trial.suggest_int('n_estimators', 200, 700, step=50),
        'max_depth':        trial.suggest_int('max_depth', 3, 9),
        'learning_rate':    trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'subsample':        trial.suggest_float('subsample', 0.6, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.9),
        'min_child_weight': trial.suggest_int('min_child_weight', 5, 20),
        'gamma':            trial.suggest_float('gamma', 0.0, 1.0),
        'reg_alpha':        trial.suggest_float('reg_alpha', 0.01, 2.0, log=True),
        'reg_lambda':       trial.suggest_float('reg_lambda', 0.2, 20, log=True),
        'eval_metric': 'logloss', 'n_jobs': -1,
        'random_state': 42, 'verbosity': 0
    }
    pipeline = Pipeline([
        ('extractor', URLFeatureExtractor(trusted_domains=TRUSTED_DOMAINS)),
        ('model',     XGBClassifier(**params))
    ])
    scores = cross_val_score(pipeline, urls_sub, y_sub,
                              cv=cv, scoring='roc_auc', n_jobs=-1)
    return scores.mean()


def objective_lgbm(trial):
    params = {
        'n_estimators':      trial.suggest_int('n_estimators', 200, 700, step=50),
        'max_depth':         trial.suggest_int('max_depth', 3, 9),
        'learning_rate':     trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'num_leaves':        trial.suggest_int('num_leaves', 20, 250),
        'subsample':         trial.suggest_float('subsample', 0.6, 0.9),
        'colsample_bytree':  trial.suggest_float('colsample_bytree', 0.6, 0.9),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),
        'reg_alpha':         trial.suggest_float('reg_alpha', 0.01, 1.0, log=True),
        'reg_lambda':        trial.suggest_float('reg_lambda', 0.1, 10, log=True),
        'n_jobs': -1, 'random_state': 42, 'verbose': -1
    }
    pipeline = Pipeline([
        ('extractor', URLFeatureExtractor(trusted_domains=TRUSTED_DOMAINS)),
        ('model',     LGBMClassifier(**params))
    ])
    scores = cross_val_score(pipeline, urls_sub, y_sub,
                              cv=cv, scoring='roc_auc', n_jobs=-1)
    return scores.mean()

# 4. Run Optuna Studies

N_TRIALS = 30
studies  = {}

for model_name, objective in [('XGBoost', objective_xgb),
                               ('LightGBM', objective_lgbm)]:
    print(f"â”€â”€ Tuning {model_name} ({N_TRIALS} trials) â”€â”€")
    study = optuna.create_study(
        direction='maximize',
        sampler=optuna.samplers.TPESampler(seed=42)
    )
    study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)
    studies[model_name] = study
    print(f"  Best AUC    : {study.best_value:.6f}")
    print(f"  Best params : {study.best_params}\n")

# 5. Retrain on Full Data & Evaluate

model_constructors = {
    'XGBoost':  lambda p: XGBClassifier(
        **p, eval_metric='logloss', n_jobs=-1, random_state=42, verbosity=0),
    'LightGBM': lambda p: LGBMClassifier(
        **p, n_jobs=-1, random_state=42, verbose=-1),
}

BEST_PIPELINES = {}
tuned_results  = {}

print("=" * 68)
print("FINAL EVALUATION â€” Best Tuned Models on Full Test Set")
print("=" * 68)
print(f"\n{'Model':<22} {'Acc %':>8} {'F1 %':>8} {'AUC':>8} "
      f"{'PRAUC':>8} {'FP':>7} {'FN':>7} {'Time':>7}")
print("─" * 75)

for name, study in studies.items():
    pipeline = Pipeline([
        ('extractor', URLFeatureExtractor(trusted_domains=TRUSTED_DOMAINS)),
        ('model',     model_constructors[name](study.best_params))
    ])

    t0 = time.time()
    pipeline.fit(train_urls, y_train)
    elapsed = time.time() - t0

    preds = pipeline.predict(test_urls)
    proba = pipeline.predict_proba(test_urls)[:, 1]
    tn, fp, fn, tp = confusion_matrix(y_test, preds).ravel()

    acc   = accuracy_score(y_test, preds) * 100
    f1    = f1_score(y_test, preds) * 100
    auc   = roc_auc_score(y_test, proba)
    prauc = average_precision_score(y_test, proba)

    BEST_PIPELINES[name] = pipeline
    tuned_results[name]  = {
        'Accuracy (%)': round(acc, 4),
        'F1 (%)':       round(f1, 4),
        'ROC-AUC':      round(auc, 6),
        'PR-AUC':       round(prauc, 6),
        'FP':           int(fp),
        'FN':           int(fn),
        'Best CV AUC':  round(study.best_value, 6),
        'Time':         f"{elapsed:.1f}s"
    }
    print(f"{name:<22} {acc:>8.2f} {f1:>8.2f} {auc:>8.4f} {prauc:>8.4f} "
          f"{fp:>7,} {fn:>7,} {elapsed:>6.1f}s")

tuned_df = pd.DataFrame(tuned_results).T.sort_values('ROC-AUC', ascending=False)
print(f"\n{'─'*75}")
print("\n=== TUNED RESULTS ===")
print(tuned_df.to_string())

# 6. Tuned vs Baseline Comparison

baseline_df = pd.read_csv('reports/results_baseline.csv', index_col=0)
baseline    = baseline_df['ROC-AUC'].to_dict()

print("\n=== TUNED vs BASELINE ===\n")
print(f"{'Model':<22} {'Baseline AUC':>14} {'Tuned AUC':>12} {'Gain':>8}")
print("─" * 58)
for name in studies:
    base  = baseline.get(name, 0)
    tuned = tuned_results[name]['ROC-AUC']
    print(f"{name:<22} {base:>14.4f} {tuned:>12.4f} {tuned - base:>+8.4f}")
