# -*- coding: utf-8 -*-
"""04_shap_explainability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqWZxZC0bDMSrTDblCSMraulLtvjQK7G
"""

!pip install shap datasets --quiet

import os, pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap
from datasets import load_dataset

import sys
sys.path.append('..')

os.makedirs('reports/figures', exist_ok=True)

# 1. Load Data & Model

print("Loading PhreshPhish test split...")
df_train = pd.read_csv('data/df_train.csv')
df_test  = pd.read_csv('data/df_test.csv')

df_test['binary_label'] = (df_test['label'] == 'benign').astype(int)
df_train['binary_label'] = (df_train['label'] == 'benign').astype(int)

best_pipeline = pickle.load(open('models/best_pipeline_tuned.pkl', 'rb'))
extractor     = best_pipeline.named_steps['extractor']
model         = best_pipeline.named_steps['model']

print(f"Model   : {type(model).__name__}")
print(f"Classes : {model.classes_}  (0=phishing, 1=benign)")

# 2. Extract Features & Compute SHAP Values

test_urls  = df_test['url'].values
y_test     = df_test['binary_label'].values

print("Extracting features...")
X_test_feat   = extractor.transform(test_urls)
feature_names = X_test_feat.columns.tolist()
print(f"Feature matrix : {X_test_feat.shape}")

print("\nComputing SHAP values...")
background_urls = df_train['url'].sample(2000, random_state=42).values
X_background    = extractor.transform(background_urls)
X_explain       = X_test_feat.sample(2000, random_state=42)

explainer   = shap.TreeExplainer(model, X_background)
shap_values = explainer.shap_values(X_explain)

# For binary classification shap_values may be list [class0, class1]
sv = shap_values[0] if isinstance(shap_values, list) else shap_values
print(f"SHAP values shape : {sv.shape}  âœ…")

# Plot 1 Beeswarm Summary

plt.figure(figsize=(12, 8))
shap.summary_plot(
    sv, X_explain,
    feature_names=feature_names,
    plot_type='dot',
    max_display=21,
    show=False
)
plt.title('SHAP Summary : Feature Impact on Phishing Detection',
          fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('reports/figures/shap_summary_beeswarm.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("Saved at shap_summary_beeswarm.png âœ…")

# Plot 2 : Bar Importance

plt.figure(figsize=(12, 8))
shap.summary_plot(
    sv, X_explain,
    feature_names=feature_names,
    plot_type='bar',
    max_display=21,
    show=False
)
plt.title('SHAP Feature Importance : Mean |SHAP Value|',
          fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('reports/figures/shap_importance_bar.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("Saved at shap_importance_bar.png")

# ## Plot 3 : Waterfall Plots (3 phishing + 3 benign)

phish_idx = df_test[df_test['binary_label'] == 0].index[:3]
legit_idx  = df_test[df_test['binary_label'] == 1].index[:3]

explain_idx  = list(phish_idx) + list(legit_idx)
explain_urls = df_test.loc[explain_idx, 'url'].values
explain_feat = extractor.transform(explain_urls)
explain_sv   = explainer.shap_values(explain_feat)
if isinstance(explain_sv, list):
    explain_sv = explain_sv[0]

base_val = (explainer.expected_value
            if not isinstance(explainer.expected_value, list)
            else explainer.expected_value[0])

labels = ['PHISHING'] * 3 + ['BENIGN'] * 3

for i, (url, label) in enumerate(zip(explain_urls, labels)):
    print(f"\n       {label}: {url[:80]}{'...' if len(url)>80 else ''}")

    plt.figure(figsize=(14, 4))
    shap.waterfall_plot(
        shap.Explanation(
            values        = explain_sv[i],
            base_values   = base_val,
            data          = explain_feat.iloc[i].values,
            feature_names = feature_names
        ),
        max_display=12,
        show=False
    )
    plt.title(f'{label} : {url[:60]}{"..." if len(url)>60 else ""}',
              fontsize=11, fontweight='bold')
    plt.tight_layout()
    fname = f'reports/figures/shap_waterfall_{label.lower()}_{i}.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Saved at {fname}...")

# Plot 4 : Dependence Plots (Top 4 features)

mean_shap     = np.abs(sv).mean(axis=0)
top4_idx      = np.argsort(mean_shap)[::-1][:4]
top4_features = [feature_names[i] for i in top4_idx]
print(f"Top 4 features: {top4_features}")

fig, axes = plt.subplots(2, 2, figsize=(16, 10))
axes = axes.flatten()

for ax, feat in zip(axes, top4_features):
    feat_idx = feature_names.index(feat)
    shap.dependence_plot(
        feat_idx, sv, X_explain,
        feature_names=feature_names,
        ax=ax, show=False
    )
    ax.set_title(f'SHAP Dependence : {feat}', fontweight='bold')

plt.suptitle('Feature Dependence Plots â€” How Feature Values Drive Predictions',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('reports/figures/shap_dependence.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("Saved at shap_dependence.png âœ…")

# Feature Ranking Table

mean_shap_series = (pd.Series(mean_shap, index=feature_names)
                    .sort_values(ascending=False))

print("=== SHAP FEATURE RANKING ===\n")
print(f"{'Rank':<6} {'Feature':<30} {'Mean |SHAP|':>12}")
print("─" * 50)
for rank, (feat, val) in enumerate(mean_shap_series.items(), 1):
    print(f"{rank:<6} {feat:<30} {val:>12.4f}")

print("\n=== KEY INSIGHTS (Top 3) ===\n")
for feat, val in mean_shap_series.head(3).items():
    feat_shap = sv[:, feature_names.index(feat)]
    feat_vals = X_explain[feat].values
    corr      = np.corrcoef(feat_vals, feat_shap)[0, 1]
    direction = "HIGH values at phishing" if corr > 0 else "LOW values at phishing"
    print(f"  {feat}")
    print(f"    Mean |SHAP| : {val:.4f}")
    print(f"    Direction   : {direction}\n")